config/routes.rb
Rails.application.routes.draw do
  root 'themes#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources 'themes', shallow: true do
    resources 'codes'
  end
  resources 'users'
  resources 'times'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
  belongs_to :user
  belongs_to :theme
  has_one :code_time, dependent: :destroy

  validates :content, presence: true
  validate :prevent_invalid_code

  def prevent_invalid_code
    return if content.nil?

    errors.add(:content, 'is invalid.') unless content.include?('(time') && content.include?('#lang racket')
  end
end

app/models/code_time.rb
class CodeTime < ApplicationRecord
  belongs_to :code

  validates :time, presence: true
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :codes, dependent: :destroy
  has_many :theme_images, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/models/theme_image.rb
class ThemeImage < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :theme
  validate :unique_name

  def unique_name
    errors.add(:image, 'has already been taken') if Dir.open("public/uploads/theme_images/",&:to_a).include?(image.to_s.reverse.sub!(/\/.*/, "").reverse)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :codes, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper

  add_flash_types :success, :info, :warning, :danger

  def authorize
    redirect_to login_path, danger: 'ログインしてください' unless logged_in?
  end

  def authorized
    redirect_to root_path, warning: 'その操作はできません' if logged_in?
  end

  def admin_user
    redirect_to(root_path, danger: "管理者以外は、その操作はできません") unless current_user.admin?
  end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :authorize, only: %i[new create destroy]

  def new
    @code = Code.new
  end

  def create
    @code = current_user.codes.build(code_params)
    @code.theme_id = params[:theme_id]
    if @code.save
      redirect_to @code, success: '提出に成功しました'
    else
      render 'new'
    end
  end

  def show
    @code = Code.find(params[:id])
  end

  def destroy
    Code.find(params[:id]).destroy
    flash[:success] = "Code deleted"
    redirect_to root_path
  end

  private

  def code_params
    params.require(:code).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authorized, only: %i[new create]

  def new; end

  def create
    user = User.find_by(name: params[:name])
    if user&.authenticate(params[:password])
      log_in user
      redirect_to root_path
    else
      redirect_to login_path, danger: '名前かパスワードが間違っています'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :authorize, only: %i[new create edit update destory]
  before_action :admin_user, only: %i[destroy]

  def index
    @themes = []

    @users = User.all
    h = Hash.new
    @users.each do |user|
      h.store(user.name, 0)
    end

    Theme.all.each do |theme|
      rank = Code.joins(:code_time).eager_load(:code_time).where(theme_id: theme.id).order(:time)
      new_code = Code.joins(:code_time).eager_load(:code_time).where(theme_id: theme.id).order(:created_at).last

      if rank.first.nil?
        @themes.push([theme])
      elsif (Time.now - rank.first.created_at) < 24.hours && (Time.now - new_code.created_at) < 24.hours
        @themes.push([theme, rank.first.user, rank.count, "code", "top"])
      elsif (Time.now - rank.first.created_at) < 24.hours
        @themes.push([theme, rank.first.user, rank.count, "top"])
      elsif (Time.now - new_code.created_at) < 24.hours
        @themes.push([theme, rank.first.user, rank.count, "code"])
      else
        @themes.push([theme, rank.first.user, rank.count])
      end

      rank.each_with_index do |code, i|
        if i < 10 #10位以下はポイントなし
          h.store(code.user.name, h[code.user.name] + (100 / (i + 1)))
        end
      end
    end

    @themes.reverse!

    @points = h.sort_by{ | k, v | v }.reverse
  end

  def new
    @theme = Theme.new
  end
  
  def create
    image_error = false
    @theme = Theme.new(theme_params)
    if @theme.save
      params[:theme][:image]&.each do |i|
        image = ThemeImage.new(theme_id: @theme.id, image: i)
        unless image.save
          image_error = true
          break
        end
      end
      if image_error
        flash.now[:danger] = "画像のアップロードに失敗しました。ファイル形式、ファイルサイズ、ファイル名を確認してください。"
        render :edit
      else
        redirect_to @theme, success: '問題を作成しました'
      end
    else
      render :new
    end
  end

  def show
    @theme = Theme.find(params[:id])
    @codes = Code.joins(:code_time).eager_load(:code_time).where(theme_id: @theme.id).order(:time)
  end

  def edit
    @theme = Theme.find(params[:id])
  end

  def update
    image_error = false
    @theme = Theme.find(params[:id])
    if @theme.update(theme_params)
      params[:theme][:checked_images]&.each do |i|
        ThemeImage.find(i).destroy
      end
      params[:theme][:image]&.each do |i|
        image = ThemeImage.new(theme_id: @theme.id, image: i)
        unless image.save
          image_error = true
          break
        end
      end
      if image_error
        flash.now[:danger] = "画像のアップロードに失敗しました。ファイル形式、ファイルサイズ、ファイル名を確認してください。"
        render :edit
      else
        redirect_to @theme, success: '問題を更新しました'
      end
    else
      render :edit
    end
  end

  def destroy
    Theme.find(params[:id]).destroy
    redirect_to root_path, success: "問題を削除しました"
  end

  private

  def theme_params
    params.require(:theme).permit(:title, :body)
  end
end

app/controllers/times_controller.rb
class TimesController < ApplicationController
  before_action :authorize, only: %i[create]

  def create
    @code = Code.find(params[:time][:code_id])
    Dir.chdir("public/uploads/theme_images/") do
      File.open('test.rkt', 'w') do |text|
        text.puts(@code.content)
      end
      uptime = `uptime`
      uptime = uptime.split.last(3).first.to_f
      code_out_put = `racket test.rkt`
      cpu_time = code_out_put.match(/time:/).post_match.to_i
      @code_time = CodeTime.new(code_id: @code.id,
                                time: cpu_time,
                                out_put: code_out_put,
                                uptime: uptime)
      if code_out_put != "" && @code_time.save
        redirect_to @code_time.code, success: '計測に成功しました'
      else
        redirect_to @code, danger: '計測に失敗しました'
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, only: %i[new create destroy]
  before_action :admin_user, only: :destroy

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path, success: '新規登録に成功しました！'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def inform_validation_error(obj)
    html_text = ''
    obj.errors.full_messages.each do |message|
      html_text += content_tag(:div, class: 'alert alert-danger') do
        content_tag(:a, 'x', data: { dismiss: 'alert' })
        message
      end
    end
    raw(html_text)
  end

  def simple_time(time)
    time.strftime("%Y-%m-%d　%H:%M　")
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/themes_helper.rb
module ThemesHelper
  def hide_code_time(code)
    Time.now - code.code_time.created_at < 60 * 60 * 24 * 7 #7日間
  end
end

app/helpers/times_helper.rb
module TimesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/codes/new.html.erb
<h1>コード提出</h1>

<h3>注意点</h3>
<ul>
  <li>動作確認してから提出する</li>
  <li>現在はracketのみ対応</li>
  <li>例のように、timeで囲む</li>
</ul>

<pre style="background-color: #F7F7F7;">
  例
  <code>
    #lang racket
    (time (apply * (range 1 1000)))
  </code>
</pre>

<%= form_with model: @code, url: theme_codes_path(theme_id: params[:theme_id]), local: true do |f| %>
  <%= inform_validation_error @code %>
  <p>コード</p>
  <%= f.text_area :content, class: 'form-control', style: "height: 50vh;" %>
  <%= f.submit '提出', class: 'btn btn-primary' %>
<% end %>

app/views/codes/show.html.erb
<h1>コード詳細</h1>

<h3><%= link_to @code.theme.title, theme_path(@code.theme) %></h3>

<div class="code" style="background-color: aliceblue">
  <pre><code><%= @code.content %></code></pre>
</div>

<% if  logged_in? && (current_user.admin? || current_user == @code.user) %>
  <%= link_to "delete", @code, method: :delete,
              data: { confirm: "You sure?" }, class: "btn btn-danger",
              style: 'float: right; margin-right: 20px;' %>
<% end %>
<hr>
<p>提出者:　<%= link_to @code.user.name, user_path(@code.user) %></p>
<p>提出日時：　<%= simple_time @code.created_at %></p>
<hr>

<% unless @code.code_time.nil? %>
  <p>タイム：　<%= link_to "#{@code.code_time.time.to_s} [ms]", theme_path(@code.theme) %></p>
  <p>計測日時：　<%= simple_time @code.code_time.created_at %></p>
  <p>計測時のuptime：　<%= @code.code_time.uptime %></p>

  <hr>
  <p>出力</p>
  <div class="code" style="background-color: #EFEFEF"><%= simple_format @code.code_time.out_put %></div>
<% else %>

  <%= form_with url: times_path(time: {code_id: @code.id}) do |f| %>
    <%= f.submit '計測', data: { "disable-with": "計測しています..." } %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted text-center">© 2019 <a href="https://github.com/rkdora/collatz_rank">rkdora</a>, v2.15</p>
  </div>
</footer>

app/views/layouts/_header.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark mt-3 mb-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <%= link_to 'Collatz Rank', root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'コード一覧', codes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'ユーザーリスト', users_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item active">
            <%= link_to current_user.name, user_path(id: current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'コード提出', new_code_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<% flash.each do |name, msg| %>
  <div class="container">
    <div class="alert alert-<%= name %>">
      <%= msg.html_safe %>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark mt-3 mb-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <%= link_to 'Ryuto Circuit', root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to '1Day100', "http://1day100.melt.kyutech.ac.jp/", target: :_blank, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'レーサーリスト', users_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item active">
            <%= link_to current_user.name, user_path(id: current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<% flash.each do |name, msg| %>
  <div class="container">
    <div class="alert alert-<%= name %>">
      <%= msg.html_safe %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ryuto Circuit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div id="wrapper"><div class="container"><%= yield %></div></div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/themes/_changes.html.erb
<h2>Changes</h2>

<ul>
  <li>2.15 問題の画像をコード内で使えるように & 問題の編集権限を解放 2019-07-30</li>
  <li>2.14.2 画像の削除が可能に（管理者のみ） & 画像のファイル名表示 & 対応するファイル形式は「jpg jpeg gif png」のみ　2019-07-30</li>
  <li>2.14.1 問題一覧を新しい問題が上になるように 2019-07-30</li>
  <li>2.14 問題に画像(~5MB)をアップロードできるように 2019-07-26</li>
  <li>2.13 ポイントを棒グラフで表示 2019-06-16</li>
  <li>2.12.1 タイム表示のバグ修正 2019-06-14</li>
  <li>2.12 問題の横に、計測済コードの数を表示 2019-06-10</li>
  <li>2.11 一位が新しくなったら一位の名前を赤に、新しい投稿があったらタイトルを赤に、両方新しくなったら両方赤に。 2019-06-10</li>
  <li>2.10 計測時のuptimeを記録。過去のuptimeは、0.0とする。　2019-06-10</li>
  <li>2.9 回答ゼロの問題の文字色を薄い青色に　2019-06-06</li>
  <li>2.8.1 pre内の文章の折り返し化　2019-06-06</li>
  <li>2.8 1位が新しくなった問題（計測から24時間以内）の文字色を赤に（トップページ）　2019-06-05</li>
  <li>2.7 問題内のランキングをテーブル表示 & 計測日時を等幅フォント　2019-06-05</li>
  <li>2.6 問題内のコードインデント対応　2019-06-05</li>
  <li>2.5 レーサーランキング & 問題の横にトップレーサー名を表示　2019-06-04</li>
  <li>2.4 ランキングトップのコードを７日間隠す & テーマ編集可能（管理者のみ）　2019-05-30</li>
  <li>2.3 自分のコードを削除できるように & 時間を東京時間に　2019-05-29</li>
  <li>2.2 管理者ユーザーのみ、各種データの削除が可能に　2019-05-28</li>
  <li>2.1 細かなバグの修正（コード提出後、計測せずにページ遷移できない等）　2019-05-25</li>
  <li>2.0 複数のランキングを作成することができるように　2019-05-23</li>
  <li>バージョン1.0 からスタート　2019-05-19</li>
</ul>

app/views/themes/edit.html.erb
<h1>問題編集</h1>

<%= form_with model: @theme, local: true do |f| %>
  <%= inform_validation_error @theme %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  <%= f.label :body %>
  <%= f.text_area :body, class: 'form-control', style: "height: 50vh;" %>
  <p>回答例を載せましょう。</p>
  <%= f.label :image %></br>
  <p>削除する画像を選択してください</p>
  <% @theme.theme_images.each do |i| %>
    <%= image_tag i.image.url, width: 300 %>
    <%= f.check_box :checked_images, {multiple: true, include_hidden: false}, i.id %>
  <% end %><br/>
  <br />
  ※画像は5MBまで</br>
  ※ファイル名の重複禁止</br>
  ※ファイル形式は、「jpg jpeg gif png」のみ</br>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.submit '更新', class: 'btn btn-primary' %>
<% end %>

app/views/themes/index.html.erb
<h2>問題一覧</h2>
<% @themes.each do |theme| %>
  <h3>
    <% if theme.length >= 4 && theme[3] == "code" %>
      <%= link_to theme[0].title, theme_path(theme[0]), class: "text-danger" %>
    <% elsif theme.length == 1 %>
      <%= link_to theme[0].title, theme_path(theme[0]), class: "text-info" %>
    <% else %>
      <%= link_to theme[0].title, theme_path(theme[0]) %>
    <% end %>

    <% if theme.last == "top" %>
      <small class="text-danger">　<%= theme[1].name %></small>
    <% elsif theme.length > 1 %>
      <small>　<%= theme[1].name %></small>
    <% end %>

    <% if theme.length > 1 %>
      <small>/ <%= theme[2] %></small>
    <% end %>

    <% if logged_in? && current_user.admin? %>
      | <%= link_to "delete", theme[0], method: :delete,
                  data: { confirm: "You sure?" } %>
    <% end %>
  </h3>
<% end %>

<% if logged_in? %>
  <%= link_to '問題作成', new_theme_path, class: "btn btn-primary" %>
<% end %>

<hr>

<h2>レーサーランキング</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>順位</th>
      <th>名前</th>
      <th>ポイント</th>
    </tr>
  </thead>
  <tbody>
    <% @points.each_with_index do |point, i| %>
      <tr>
        <% if i == 0 %>
          <td>🥇</td>
        <% elsif i == 1%>
          <td>🥈</td>
        <% elsif i == 2 %>
          <td>🥉</td>
        <% else %>
          <td>第<%= i + 1 %>位</td>
        <% end %>
        <td><%= point[0] %></td>
        <td>
          <% (point[1] / 10).times do %>
            <span style="color: royalblue; letter-spacing: -9px;">|</span>
          <% end %>
          &nbsp;<%= point[1] %>pt
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>ポイント = (100 ÷ 問題内の順位(10位以内))の総和</p>
<hr>
<%= render 'themes/changes' %>

app/views/themes/new.html.erb
<h1>問題作成</h1>

<%= form_with model: @theme, local: true do |f| %>
  <%= inform_validation_error @theme %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  <%= f.label :body %>
  <%= f.text_area :body, class: 'form-control', style: "height: 50vh;" %>
  <p>回答例を載せましょう。</p>
  <%= f.label :image %></br>
  <br />
  ※画像は5MBまで</br>
  ※ファイル名の重複禁止</br>
  ※ファイル形式は、「jpg jpeg gif png」のみ</br>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.file_field :image, multiple: true %>
  <%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>

app/views/themes/show.html.erb
<h1><%= @theme.title %></h1>

<% unless @theme.body.nil? %>
  <div class="code">
    <pre><code><%= @theme.body %></code></pre>
  </div>
<% end %>
<div class="cf">
  <% @theme.theme_images.each do |i| %>
    <div class="fl">
      <%= image_tag i.image.url, width: 300 %><br />
      <%= i.image.to_s.reverse.sub!(/\/.*/, "").reverse %>
    </div>
  <% end %>
</div>
<% if logged_in? %>
  <%= link_to '編集', edit_theme_path(@theme), class: "btn btn-warning" %>
<% end %>
<hr>

<%= link_to '提出', new_theme_code_path(@theme), class: "btn btn-lg btn-primary" %>

<hr>

<% if @codes.length.zero? %>
  <h4>計測済みのコードはありません</h4>
<% else %>
  <h2>ランキング</h2>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>順位</th>
      <th>名前</th>
      <th>タイム</th>
      <th>計測日時</th>
    </tr>
    </thead>
    <tbody>
    <% @codes.each_with_index do |code, i| %>
      <tr>
        <% if i == 0 %>
          <td>🥇</td>
        <% elsif i == 1%>
          <td>🥈</td>
        <% elsif i == 2 %>
          <td>🥉</td>
        <% else %>
          <td>第<%= i + 1 %>位</td>
        <% end %>
        <td><%= code.user.name %></td>
        <% if (logged_in? && (current_user.admin? || current_user == code.user)) || (!i.zero? || !hide_code_time(code)) %>
          <td>
            <%= link_to "#{code.code_time.time.to_s}[ms]", code_path(code), class: 'text-monospace' %>
          </td>
        <% else %>
          <td>
            <%= "#{code.code_time.time.to_s}[ms]" %>
          </td>
        <% end %>
        <td><%= simple_time code.code_time.created_at %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <p>ランキングトップのコードは、計測時から7日間を過ぎるまで詳細確認することはできません。</p>
<% end %>

app/views/users/index.html.erb
<h1>レーサーリスト</h1>

<% @users.each do |user| %>
  <%= link_to user.name, user_path(user)%>
  <% if logged_in? && current_user.admin? %>
    | <%= link_to "delete", user, method: :delete,
                  data: { confirm: "You sure?" } %>
  <% end %>
  <hr>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, local: true do |f| %>
  <%= inform_validation_error @user %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.label :password%>
  <%= f.password_field :password, class: 'form-control' %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <%= f.submit 'Sign Up', class: 'btn btn-primary' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>